### ISSUE TITLE
Code consistentie

### ISSUE THREAD

**Issue by MonikaaS** [LarsBreuren/web-app-from-scratch-1920#2]
- Bovenste gedeelte van je code gebruik je netjes const en let. Maar vanaf regel 26 begin je inene var te gebruiken

- Probeer ook op de consistentie te letten van je punt komma. Bijvoorbeeld regel 10 niet en bij regel 22 weer wel 

- soms gebruik je arrow functions en soms normale functions

**Comment by joostf** [comment]
Indenting lijkt ook niet heel netjes?
